from siena.shared.exceptions.base import SIENABaseException


class SIENACLIException(SIENABaseException):
    pass
